# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2022 smdn <smdn@smdn.jp>"

name: Run tests for implementations

permissions: {}

on:
  push:
    branches: [main]
    paths:
      - "src/impls/**/*"
      - "!src/impls/**/.editorconfig"
      - "!src/impls/**/.gitignore"
      - "!src/impls/**/README.md"
      - "tests/impls/**/*"

  pull_request:
    types:
      - opened
      - review_requested
      - synchronize
    paths:
      - "src/impls/**/*"
      - "!src/impls/**/.editorconfig"
      - "!src/impls/**/.gitignore"
      - "!src/impls/**/README.md"
      - "tests/impls/**/*"

  workflow_dispatch:
    inputs:
      os:
        description: "The OS label which run the test on. (ex: ubuntu-latest, windows-latest, macos-latest)"
        required: false
        type: string
      target-impl:
        description: "The target implementation ID to run the tests."
        required: false
        type: string
      verbose:
        description: "If true, enables verbose output."
        required: false
        type: boolean
        default: false

env:
  # cSpell:disable
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SDK_MINIMUM_VERSION: "10.0.100"
  NODEJS_MINIMUM_VERSION: 20
  JAVA_MINIMUM_VERSION: 21
  GPP_MINIMUM_VERSION: 14
  # cSpell:enable

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-slim
    permissions:
      contents: read
    outputs:
      runs-ons: ${{ steps.runs-on-os-list.outputs.runs-ons }}
      target-impls: ${{ steps.test-target-impls.outputs.target-impls }}
    env:
      RUNS_ON_OS_LIST_DEFAULT: "['ubuntu-latest', 'windows-latest', 'macos-latest', 'ubuntu-24.04-arm', 'windows-11-arm' ]"

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine OS list which run the tests on
        id: runs-on-os-list
        shell: pwsh
        run: |
          $verbose = '${{ inputs.verbose }}' -ieq 'true'
          $os_list = $Env:RUNS_ON_OS_LIST_DEFAULT | ConvertFrom-Json

          if ( ! [string]::IsNullOrEmpty( '${{ inputs.os }}' ) ) {
            $os_list = @('${{ inputs.os }}')
          }

          if ( $verbose ) {
            "::notice::test runs on: $($os_list -join ', ')"
          }

          "runs-ons=$($os_list | ConvertTo-Json -Compress)" >> $Env:GITHUB_OUTPUT

      - name: Determine target implementation list which run the tests to
        id: test-target-impls
        shell: pwsh
        run: |
          $verbose = '${{ inputs.verbose }}' -ieq 'true'
          $target_impls = Get-Content ./tests/impls/implementations.jsonc | ConvertFrom-Json | Select-Object -ExpandProperty ImplementationId | Get-Unique

          if ( ! [string]::IsNullOrEmpty( '${{ inputs.target-impl }}' ) ) {
            $target_impls = @('${{ inputs.target-impl }}')
          }

          if ( $verbose ) {
            "::notice::target implementations: $($target_impls -join ', ')"
          }

          "target-impls=$($target_impls | ConvertTo-Json -Compress)" >> $Env:GITHUB_OUTPUT

  run-tests:
    name: Test '${{ matrix.target-impl }}' on ${{ matrix.os }}
    needs: [setup]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - ${{ fromJson(needs.setup.outputs.runs-ons) }}
        target-impl:
          - ${{ fromJson(needs.setup.outputs.target-impls) }}

    steps:
      - name: Checkout repository
        background: true
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare .NET SDK ${{ env.DOTNET_SDK_MINIMUM_VERSION }}
        background: true
        uses: smdn/workflows-dotnet/actions/prepare-dotnet-sdk@ca77c33b60b27d8734f7e7cc02f97a9b274c6779 # actions/prepare-dotnet-sdk/v1.3.0
        if: ${{ matrix.target-impl == 'csharp' || matrix.target-impl == 'visualbasic' }}
        with:
          minimal_dotnet_sdk_version: '${{ env.DOTNET_SDK_MINIMUM_VERSION }}'

      - name: Setup Java
        background: true
        if: ${{ matrix.target-impl == 'java' }}
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          # cSpell:disable-next-line
          distribution: 'temurin'
          java-version: ${{ env.JAVA_MINIMUM_VERSION }}

      - name: Setup Node.js
        background: true
        if: ${{ matrix.target-impl == 'javascript' }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODEJS_MINIMUM_VERSION }}

      - name: Setup MSBuild
        background: true
        if: ${{ runner.os == 'Windows' && (matrix.target-impl == 'c' || matrix.target-impl == 'cpp') }}
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Setup mypy
        background: true
        if: ${{ matrix.target-impl == 'python' }}
        run: pip install mypy

      - name: Setup g++
        background: true
        if: ${{ runner.os == 'Linux' && matrix.target-impl == 'cpp' }}
        # Check if the current g++ version is lower than GPP_MINIMUM_VERSION.
        # Automatically fall back to the compliant pre-installed g++ binary via GITHUB_PATH.
        # This is achieved by creating a symlink under the $HOME directory and prioritizing it.
        run: |
          GPP_CURRENT_VERSION=$(g++ -dumpversion | cut -d. -f1)

          if [ "$GPP_CURRENT_VERSION" -lt "$GPP_MINIMUM_VERSION" ]; then
            TARGET_GPP="g++-${GPP_MINIMUM_VERSION}"

            if command -v "$TARGET_GPP" >/dev/null 2>&1; then
              echo "Current g++ version ($GPP_CURRENT_VERSION) is less than $GPP_MINIMUM_VERSION. Switching to $TARGET_GPP."

              mkdir -p $HOME/.local/bin
              ln -sf $(which "$TARGET_GPP") $HOME/.local/bin/g++

              echo "$HOME/.local/bin" >> $GITHUB_PATH
            else
              echo "Warning: Current g++ ($GPP_CURRENT_VERSION) is less than $GPP_MINIMUM_VERSION, but $TARGET_GPP was not found in the system."
            fi
          else
            echo "Current g++ version ($GPP_CURRENT_VERSION) is already $GPP_MINIMUM_VERSION or higher. Keeping default."
          fi

      - name: Wait for prerequisite steps
        wait-all:

      - name: Run tests with ${{ matrix.target-impl }} on ${{ matrix.os }}
        shell: pwsh
        run: |
          $verbose = '${{ inputs.verbose }}' -ieq 'true'
          $run_tests_options = @(
            '--target-impl', '${{ matrix.target-impl }}'
          )

          if ($verbose) {
            $run_tests_options += "-v"
          }

          if ($verbose) {
            "pwsh tests/impls/run-tests.ps1 $($run_tests_options -join ' ')"
          }

          pwsh tests/impls/run-tests.ps1 $run_tests_options
